import types
from timm.models import TNT

# TODO: nn.Unfold
def aggregate_tnt(model, variant=None):
    if isinstance(model, TNT):
        def build_downsample(self, cfg=None):
            self.downsample_layers = [
                {'name': 'pixel_embed/proj', 'type': 'conv', 'kwargs': {}}, # 4
            ]
        model.build_downsample = types.MethodType(build_downsample, model)
        return True, model
    return False, model

'''
TNT(
  (pixel_embed): PixelEmbed(
    (proj): Conv2d(3, 24, kernel_size=(7, 7), stride=(4, 4), padding=(3, 3))
    (unfold): Unfold(kernel_size=[4, 4], dilation=1, padding=0, stride=[4, 4])
  )
  (norm1_proj): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
  (proj): Linear(in_features=384, out_features=384, bias=True)
  (norm2_proj): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
  (pos_drop): Dropout(p=0.0, inplace=False)
  (blocks): ModuleList(
    (0): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (1): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (2): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (3): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (4): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (5): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (6): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (7): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (8): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (9): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (10): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
    (11): Block(
      (norm_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (attn_in): Attention(
        (qk): Linear(in_features=24, out_features=48, bias=False)
        (v): Linear(in_features=24, out_features=24, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=24, out_features=24, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (norm_mlp_in): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (mlp_in): Mlp(
        (fc1): Linear(in_features=24, out_features=96, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=96, out_features=24, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (norm1_proj): LayerNorm((24,), eps=1e-05, elementwise_affine=True)
      (proj): Linear(in_features=384, out_features=384, bias=True)
      (norm_out): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (attn_out): Attention(
        (qk): Linear(in_features=384, out_features=768, bias=False)
        (v): Linear(in_features=384, out_features=384, bias=False)
        (attn_drop): Dropout(p=0.0, inplace=True)
        (proj): Linear(in_features=384, out_features=384, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=True)
      )
      (drop_path): Identity()
      (norm_mlp): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=384, out_features=1536, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=1536, out_features=384, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
  )
  (norm): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
  (head): Linear(in_features=384, out_features=1000, bias=True)
)
'''