MODEL:
  VERSION: torchvision
  BACKBONE: swin_t
  NAME: Swin
DATALOADER:
  BATCH_SIZE: 64
DATA:
  INPUT:
    CROP_SIZE: 224
    ORIG_SIZE: 256
    INTERPOLATE: BILINEAR
SEARCH:
  SEARCH_SPACE: [0, 1, 2, 3]